### ISSUE TITLE
[Add] Partisan Animosity US

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#109]
# Partisan Animosity

### Strengthening Democracy Challenge
From: `Jan G. Voelkel, Michael N. Stagnaro, James Chu, Sophia Pink, Joseph S. Mernyk, Chrystal Redekopp, Matthew Cashman, James N. Druckman, David G. Rand, and Robb Willer. 2021. “Megastudy Identifying Successful Interventions to Strengthen Americans’ Democratic Attitudes.”`:

>## Partisan Animosity
> ### Items
> (The order of the items will be randomized.)
> #### (i) We would like to get your feelings toward both Democrats and Republicans. 
> We would like you to rate them using something we call the feeling thermometer.
> Ratings between 50 degrees and 100 degrees mean that you feel favorable and warm toward
> them. Ratings between 0 degrees and 50 degrees mean that you don't feel favorable toward them and that you don't care too much for them. You would rate them at the 50 degree mark if you
> don't feel particularly warm or cold toward them.
> [Add graphic]
> ##### (i.a) How would you rate Republicans?
> ##### (i.b) How would you rate Democrats?
> #### (ii) You have been anonymously and randomly matched with another participant who identifies as a [Democrat/Republican].
> You have been given 50 cents. You will now decide how to split these 50 cents between yourself and the [Democratic/Republican] participant. You can give any amount between 0 cents and 50 cents to the other participant. The other participant cannot affect the outcome you choose.
> For example:
> - If you give 0 cents, you will end up with 50 cents and the [Democratic/Republican] participant will end up with 0 cents.
> - If you give 50 cents, you will end up with 0 cents and the [Democratic/Republican] participant will end up with 50 cents.
> How many cents (if any) will you give to the [Democratic/Republican] participant?
> ### Scale
> #### (i) 101-point scale from “Very cold or unfavorable feeling” to “No feeling at all” to “Very warm or favorable feeling”
> #### (ii) 51-point scale from “0 cents” to “25 cents” to “50 cents”

From the handbook for submitters to the Strengthening Democracy Challenge `Rand, Robb Willer James Druckman. 2021. “Strengthening Democracy Challenge Handbook.” Stanford University. https://www.strengtheningdemocracychallenge.org/_files/ugd/2f07d4_a4bf6d4733784c798e0b8cdad910d8ee.pdf.`

> Partisan animosity will be measured in two ways that will be combined into a composite.
> ### Feeling Thermometer
> The first measure of partisan animosity is a so-called “feeling thermometer” rating for
> opposing partisans. The feeling thermometer question asks participants to rate how they feel
> toward Democrats and Republicans. on a 101-point scale from 0 (very cold) to 100 (very
> warm). The colder participants rate opposing partisans on the feeling thermometer, the
> stronger their partisan animosity. This measure is then defined as
> PA1 = (100 - Feeling Thermometer Score) / 100.
> Example: A participant who identifies as a Democrat reports that they feel pretty cold toward
> Republicans (a score of 28). Then, we will subtract this score from 100 (100 - 28 = 72) so that
> larger scores indicate stronger partisan animosity. Thus, the result is then a PA1 score of 72.
> ### Dictator Game
> The second measure of partisan animosity is giving in a “dictator game”. In a dictator game, a
> participant will be given an endowment of $0.50 that they can distribute among themselves
> and a real but unknown person from the opposite party. The higher the percentage of money
> participants keep for themselves, the stronger their partisan animosity. This measure is
> defined as:
> PA2 = [($0.50 - Amount given to out-partisan) / $0.50] * 100
> 19
> Example: A participant who identifies as a Republican shares $0.14 with a Democrat. Then, we
> will subtract this score from 0.50 (0.50 - 0.14 = 0.36) so that a larger score indicates stronger
> partisan animosity. Finally, we will divide this difference by the maximum amount (0.36 / 0.50
> = 0.72) and multiply the result by 100 to rescale the measure to range from 0 to 100. Thus, the
> result is then a PA2 score of 72.
> ### Composite
> The final score of partisan animosity is defined as the average of the two measures.
> PA = (PA1 + PA2) / 2.
> Example: Using the scores from the examples given above, the participant’s score is
> PA = (72 + 72) / 2 = 72.

### ANES: Evaluation of the Feeling Thermometer
From `Miller, Herbert F. Weisberg Arthur. 1979. “Evaluation of the Feeling Thermometer.” https://electionstudies.org/wp-content/uploads/2018/07/nes002241.pdf.`

### PEW
From `“American Trends Panel, Combined Final Topline.” 2016. Pew Research Center. https://doi.org/10.4135/9781412963947.n376.`

![image](https://user-images.githubusercontent.com/4304478/215335131-91a9da00-3af6-4fb8-98a3-4bf0ab8e8a57.png)

# Druckman and Levendusky
From `Druckman, James N., and Matthew S. Levendusky. 2019. “What Do We Measure When We Measure Affective Polarization?” Public Opinion Quarterly 83 (1): 114–22.`

![image](https://user-images.githubusercontent.com/4304478/215337583-48401026-31be-4bae-8f0e-5a557670f1d8.png)

### What is the purpose of this question? 
>these  measures  ask  respondents  to  evaluate  “the  Democratic  Party”  or  “the  Republican  Party.”  But  whom  do  voters  imagine  when  they   answer such questions: ordinary voters or elected officials? (Druckman and Levendusky 2019) 
- measure feeling towards regular people who are members of the other party?
- elites of the other party?

### What measures should we include?
- Feeling thermometer
- Dictator game
- Social Distance Measures
- Trait Ratings 
- Trust ratings

### What should be our format for a feeling thermometer question?
- a plain-formatted slider
- or one that looks like a thermometer
- or just a numerical entry box with verbal descriptions 
- a static image and a numerical entry box
 
Different surveys have done different things, and the way the question is asked seems to have an impact on the result (see: From `Miller, Herbert F. Weisberg Arthur. 1979. “Evaluation of the Feeling Thermometer.” https://electionstudies.org/wp-content/uploads/2018/07/nes002241.pdf.`)

For example (from `Miller, Herbert F.,  Weisberg Arthur. 1979. “Evaluation of the Feeling Thermometer.” ), we could use a "show card" with multiple labels:
![image](https://user-images.githubusercontent.com/4304478/215338788-36c49beb-ea8a-42e9-a84a-c10e69ea95f8.png)

or just a few:
![image](https://user-images.githubusercontent.com/4304478/215338802-ae54ac2a-f51d-44d4-a551-811484c6f4ab.png)

### How should we aggregate/score feeling thermometer ratings?
Why do Willer + co. use the direct measure of `100-outparty`? Why not use `inparty - outparty` to gague a net sentiment difference? people use scale differently, is that something to account for? (`Wilcox, Clyde, Lee Sigelman, and Elizabeth Cook. 1989. “Some Like It Hot: Individual Differences in Responses to Group Feeling Thermometers.” Public Opinion Quarterly 53 (2): 246–57.)

## Aggregation/scoring function

# References
- Related to https://github.com/Watts-Lab/surveys/issues/20

# Tasks

- [ ] Create a new folder in surveys w/ descriptive, easy-to-read name `superSpecialSurvey/`
- [ ] Create SurveyJS .json file (_e.g._ `superSpecialSurvey/superSpecialSurvey.json`)
- [ ] Create a .bib file citing your references for the survey (_always:_ `superSpecialSurvey/references.bib`)
- [ ] Create file with function to aggregate survey data (_e.g._ `superSpecialSurvey.score.js`)
- [ ] Create a cypress test of the survey (e.g. `superSpecialSurvey.cy.jsx`)
  - [ ] Include a line to take a screenshot at the end of every page
- [ ] Create a readme markdown file to document (_always:_ `superSpecialSurvey/README.md`)
  - [ ] Include relevant screenshots
- [ ] Create PR and link to this issue

**Comment by JamesPHoughton** [comment]
Now have partisan feeling thermometer, and also trait ratings, which can be used for parties.
