### ISSUE TITLE
[Add] Discussion Self-Insight

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#114]
# Survey Title: Discussion Self Insight

## Survey Source
Itzchakov, Guy, Netta Weinstein, Nicole Legate, and Moty Amar. 2020. “Can High Quality Listening Predict Lower Speakers’ Prejudiced Attitudes?” Journal of Experimental Social Psychology 91 (November): 104022.

## Survey Overview

How much do you feel this conversation:
- Helped you to understand yourself better?
- Made you think more deeply about the topic?
- Helped you to discover new or different insights about yourself?
- Helped you to reflect on your attitudes?
- Helped you think about things in a different way?

7-point likert: "Not at all", Moderately, "Very Much"

## Aggregation/scoring function
- mean
- standard deviaiton

# Tasks

- [x] Create a new folder in surveys w/ descriptive, easy-to-read name `superSpecialSurvey/`
- [x] Create SurveyJS .json file (_e.g._ `superSpecialSurvey/superSpecialSurvey.json`)
- [x] Create a .bib file citing your references for the survey (_always:_ `superSpecialSurvey/references.bib`)
- [x] Create file with function to aggregate survey data (_e.g._ `superSpecialSurvey.score.js`)
- [x] Create a cypress test of the survey (e.g. `superSpecialSurvey.cy.jsx`)
  - [x] Include a line to take a screenshot at the end of every page
- [x] Create a readme markdown file to document (_always:_ `superSpecialSurvey/README.md`)
  - [x] Include relevant screenshots
- [x] Create PR and link to this issue
