### ISSUE TITLE
[Add] big_5_short

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#142]
Add a new survey to the repository according to the instructions in [the package README.md](https://github.com/Watts-Lab/surveys#readme).

# Survey Title
`Ten-item Personality Inventory` (TIPI)

## Survey Source
https://www.sciencedirect.com/science/article/pii/S0092656603000461

## Survey Overview
> When time is limited, researchers may be faced with the choice of using an extremely brief measure of the Big-Five personality dimensions or using no measure at all. To meet the need for a very brief measure, 5 and 10-item inventories were developed and evaluated. Although somewhat inferior to standard multi-item instruments, the instruments reached adequate levels in terms of: (a) convergence with widely used Big-Five measures in self, observer, and peer reports, (b) test–retest reliability, (c) patterns of predicted external correlates, and (d) convergence between self and observer ratings. On the basis of these tests, a 10-item measure of the Big-Five dimensions is offered for situations where very short measures are needed, personality is not the primary topic of interest, or researchers can tolerate the somewhat diminished psychometric properties associated with very brief measures.

![image](https://github.com/Watts-Lab/surveys/assets/4304478/5e49323f-7931-46fc-97fc-3b740ef764bc)

The implementation in this paper asks students to write a number from 1-7. Instead, we should use a multiple choice question with the written descriptions "Disagree Strongly" through "Agree Strongly".

## Aggregation/scoring function
5 separate outcomes, should be normalized 0-1, from the following list:

- Extraversion: Q1, Q6 reverse coded 
- Agreeableness: Q2 reverse coded, Q7
- Conscientiousness: Q3, Q8 reverse coded
- Emotional Stability: Q4 reverse coded, Q9 
- Openness to Experiences: Q5, Q10 reverse coded 

# Tasks

- [x] Create a new folder in surveys w/ descriptive, easy-to-read name `superSpecialSurvey/`
- [x] Create SurveyJS .json file (_e.g._ `superSpecialSurvey/superSpecialSurvey.json`)
  - [x] Change the default completion page to a blank page (```"showCompletedPage": false```)
- [x] Create a .bib file citing your references for the survey (_always:_ `superSpecialSurvey/references.bib`)
- [x] Create file with function to aggregate survey data (_e.g._ `superSpecialSurvey.score.js`)
- [x] Create a cypress test of the survey (e.g. `superSpecialSurvey.cy.jsx`)
  - [x] Include a line to take a screenshot at the end of every page
- [x] Create a readme markdown file to document (_always:_ `superSpecialSurvey/README.md`)
  - [x] Include relevant screenshots
- [x] Update the package minor version
- [x] Rebuild the package using `npm run build` to update SHAs
- [x] Create PR and link to this issue

**Comment by gumillie222** [comment]
See PR #144

**Comment by JamesPHoughton** [comment]
Complete in https://github.com/Watts-Lab/surveys/pull/144
