### ISSUE TITLE
[Add] Subjective Value Inventory

### ISSUE THREAD

**Issue by xehu** [Watts-Lab/surveys#148]
Add a new survey to the repository according to the instructions in [the package README.md](https://github.com/Watts-Lab/surveys#readme).

# Survey Title: Subjective Value Inventory

## Survey Source
http://www.subjectivevalue.com/

## Survey Overview
Measures subjective outcomes of negotiation.

## Aggregation/scoring function
Average each of 4 different subscales, as well as an "overall" score and a "rapport" score (average of the last 2 subscales).

# Tasks

- [x] Create a new folder in surveys w/ descriptive, easy-to-read name `superSpecialSurvey/`
- [x] Create SurveyJS .json file (_e.g._ `superSpecialSurvey/superSpecialSurvey.json`)
  - [x] Change the default completion page to a blank page (`"showCompletedPage": false`)
- [x] Create a .bib file citing your references for the survey (_always:_ `superSpecialSurvey/references.bib`)
- [x] Create file with function to aggregate survey data (_e.g._ `superSpecialSurvey.score.js`)
- [x] Create a cypress test of the survey (e.g. `superSpecialSurvey.cy.jsx`)
  - [x] Include a line to take a screenshot at the end of every page
- [x] Create a readme markdown file to document (_always:_ `superSpecialSurvey/README.md`)
  - [x] Include relevant screenshots
- [x] Update the package minor version
- [x] Rebuild the package using `npm run build` to update SHAs
- [x] Create PR and link to this issue

**Comment by xehu** [comment]
Noting that after running `npm run test`, it hangs after a very long time .... how long is the expected time for the tests to complete @JamesPHoughton?

<img width="800" alt="Screenshot 2023-09-28 at 8 01 13 PM" src="https://github.com/Watts-Lab/surveys/assets/28793641/5a2788c4-e2e2-4327-a378-86e83dc8298d">

**Comment by JamesPHoughton** [comment]
This just opens the test runner in a separate window, and you have to click through and run the tests manually, at the moment, to see what they do. This is good from the perspective of letting you see and debug stuff, but not great from an actual acceptance testing perspective. When we push to GH, it runs through all the tests automatically and gives a report.

**Comment by xehu** [comment]
I did push to GitHub and .... some tests are definitely broken, lol! Maybe we can take a closer look tomorrow? Interestingly, it seems like most of the failed tests are ones I didn't touch, while the tests I wrote didn't show up. Do you have to "add" the cypress tests to a list somewhere?
