### ISSUE TITLE
[Add] Listening Quality - Own Listening

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#67]
# Survey Title
The Facilitating Listening Scale

## Survey Source
 (FLS; Bouskila-Yam & Kluger, 2011)

### Scale: 

- 1 Not at all       
- 2                       
- 3                       
- 4  
- 5 Moderately    
- 6                       
- 7                       
- 8  
- 9 Very much

### Stem: 
During the conversation, I felt I…
- Tried hard to understand what my partner was saying 
- Asked questions that show my understanding of my partner’s opinions
- Encouraged my partner to clarify a problem
- Expressed interest in my partner’s stories
- Listened to my partner attentively
- Paid close attention to what my partner has said
- Gave my partner time and space to talk
- Gave my partner my undivided attention
- Created a positive atmosphere for my partner to talk
- Allowed my partner to express themselves fully

# Tasks
- [ ] Create a new folder in surveys w/ descriptive, easy-to-read name `superSpecialSurvey/`
- [ ] Create SurveyJS .json file (*e.g.* `superSpecialSurvey/superSpecialSurvey.json`)
- [ ] Create a .bib file citing your references for the survey (*always:* `superSpecialSurvey/references.bib`)
- [ ] Create a readme markdown file to document (*always:* `superSpecialSurvey/README.md`) 
  - [ ] Survey purpose
  - [ ] Expected behavior
  - [ ] Design rationale
  - [ ] APA-style bibliography
- [ ] Create file with function to aggregate survey data (*e.g.* `superSpecialSurvey.score.js`)
- [ ] Create PR and link to this issue

**Comment by JamesPHoughton** [comment]
Question for @NettaWeinstein:
Are we ok changing the spelling of "Payed" to "Paid"?

**Comment by NettaWeinstein** [comment]
Yup!

From: James Houghton ***@***.***>
Date: Tuesday, 11 October 2022 at 18:21
To: Watts-Lab/surveys ***@***.***>
Cc: Netta Weinstein ***@***.***>, Mention ***@***.***>
Subject: Re: [Watts-Lab/surveys] [Add] Listening Quality - Own Listening (Issue #67)

Question for @NettaWeinstein<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNettaWeinstein&data=05%7C01%7Cn.weinstein%40reading.ac.uk%7Cfa7bfd266ccd4a17434508daabad0494%7C4ffa3bc4ecfc48c09080f5e43ff90e5f%7C0%7C0%7C638011056836619290%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RlzR5WCm%2F%2FcmWkPdOZ0SHYOMIrxW36bKIP0%2FkiTHt58%3D&reserved=0>:
Are we ok changing the spelling of "Payed" to "Paid"?

**Comment by JamesPHoughton** [comment]
complete in https://github.com/Watts-Lab/surveys/pull/85
