### ISSUE TITLE
[Add] Listening Quality - Partner Listening

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#68]
# Survey Title
The Facilitating Listening Scale

## Survey Source
 (FLS; Bouskila-Yam & Kluger, 2011)

### Scale: 
- 1 Not at all       
- 2                       
- 3                       
- 4  
- 5 Moderately    
- 6                       
- 7                       
- 8  
- 9 Very much

### Stem
My conversation partner…
- Tried hard to understand what I was saying 
- Asked questions that showed their understanding of my opinions
- Encouraged me to clarify a problem
- Expressed interest in my stories
- Listened to me attentively
- Paid close attention to what I said
- Gave me time and space to talk
- Gave me undivided attention
- Created a positive atmosphere for me to talk
- Allowed me to express myself fully

## Question for @NettaWeinstein and Tia
- are we ok changing the spelling of "Payed" to "Paid"?
- should the stem sentence begin with the same structure as in https://github.com/Watts-Lab/surveys/issues/67

# Tasks
- [ ] Create a new folder in surveys w/ descriptive, easy-to-read name `superSpecialSurvey/`
- [ ] Create SurveyJS .json file (*e.g.* `superSpecialSurvey/superSpecialSurvey.json`)
- [ ] Create a .bib file citing your references for the survey (*always:* `superSpecialSurvey/references.bib`)
- [ ] Create a readme markdown file to document (*always:* `superSpecialSurvey/README.md`) 
  - [ ] Survey purpose
  - [ ] Expected behavior
  - [ ] Design rationale
  - [ ] APA-style bibliography
- [ ] Create file with function to aggregate survey data (*e.g.* `superSpecialSurvey.score.js`)
- [ ] Create PR and link to this issue

**Comment by JamesPHoughton** [comment]
closed in https://github.com/Watts-Lab/surveys/pull/78
