### ISSUE TITLE
[Add] Panel Demographic Survey

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#70]
Add a new survey to the repository according to the instructions in [the package README.md](https://github.com/Watts-Lab/surveys#readme).

Capture demographic info in the same format as our existing panel data. Items that are relatively static and we don't expect to be influenced by the prior activity.

## Survey Title
Static and Semi-static Demographics Survey

## Survey Source
Compilation of questions from the CSS lab's existing turk panel
Also: https://github.com/Watts-Lab/surveyor/blob/main/surveys/demographics.csv

## Survey Overview 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/jamesphoughton/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/jamesphoughton/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

gender | Participant's Gender. | Options Included: Male \| Female \| Other | What is your gender? | NA
-- | -- | -- | -- | --
birth_year | Year of Birth of Participants | Numeric Value | In which year were you born? | NA
education_level | Highest Education that participant has received | Options Included: Less than a high school diploma \| High school diploma \|   Some college or vocational training \| 2-year college degree \| 4-year college   degree \| Post-college degree \| Other | What is the highest level of education you have completed? | NA
country | Participant's Country of Residence (typed in Text) | Text String with country name | In which country do you reside? | NA
income_min | The lower bound of a selected income bracket range, assumed to be USD,   and converted if otherwise listed. | Income Brackets Included: Less than $10,000 \| $10,000-$19,999 \|   $20,000-$29,999 \| $30,000-$39,999 \| $40,000-$49,999 \| $50,000-$74,999 \|   $75,000-$99,999 \| $100,000-$149,999 \| $150,000 or more | Thinking back over the past year,what was your family's annual income? | Rand et al. 2021
marital_status | Participant's Marital Status | Options Included: Single Never Married \| Married or Domestic Partnership   \| Widowed \| Divorced \| Separated | What is your marital status? | Rand et al. 2016
race | Participant's Race. Participants could choose more than one option | Options Included: White & Black or African-American & American   Indian or Alaska Native & Asian & Native Hawaiian or other Pacific   Islander & Other | Please choose one or more races that you consider yourself to be | NA
income_max | The higher bound of a selected income bracket range, assumed to be USD,   and converted if otherwise listed. | Income Brackets Included: Less than $10,000 \| $10,000-$19,999 \|   $20,000-$29,999 \| $30,000-$39,999 \| $40,000-$49,999 \| $50,000-$74,999 \|   $75,000-$99,999 \| $100,000-$149,999 \| $150,000 or more | Thinking back over the past year,what was your family's annual income? | Rand et al. 2021
time_zone | TimeZone of Residence of the Participant | NA | NA | Arechar Rand 2017 DOI:10.1007/s40881-017-0035-119
usual_time | Is Participant doing study at their usual M-Turk Work Time | Recoded to 1-0 | "Do you usually work on HITs at this time of the day"[Yes, No] | NA
employment_status | Is participant employed/what is the Participant's employement? | Recoded to the strings | "Are you currently...?" Options were:[Employed for wages,   Self-employed, Out of work and looking for work, Out of work but not   currently looking for work, A homemaker, A student, Military,Retired, Unable   to work] | NA

</body>

</html>

Notes:
- We should validate the birth year, but make it a numeric entry, which is probably easier than a dropdown, and less likely to get random clicks.
- Need to follow up about how timezone is asked

## Other questions to add:
- Is English your first language? (Yes, no)
- If no, how many years have you been speaking English? 

# Tasks
- [ ] Create a new folder in surveys w/ descriptive, easy-to-read name `superSpecialSurvey/`
- [ ] Create SurveyJS .json file (*e.g.* `superSpecialSurvey/superSpecialSurvey.json`)
- [ ] Create a .bib file citing your references for the survey (*always:* `superSpecialSurvey/references.bib`)
- [ ] Create a readme markdown file to document (*always:* `superSpecialSurvey/README.md`) 
- [ ] Create file with function to aggregate survey data (*e.g.* `superSpecialSurvey.score.js`)
- [ ] Create a cypress test of the survey (e.g. `superSpecialSurvey.cy.jsx`)
- [ ] Create PR and link to this issue

**Comment by JamesPHoughton** [comment]
@NettaWeinstein - these are demographic questions that we have in our existing panel, but the information is incomplete. I'm thinking about building this up as an exit survey to fill in gaps in our panel (and serve as redundancy for our existing data). Would you add anything?

 Your original demographic survey was tailored to the UK context, but has some additional questions we don't have here, such as english as a second language, nationality (as opposed to country of residence) and ethnicity.

**Comment by JamesPHoughton** [comment]
Interesting! Sounds like we may want to structure a demographics survey that adjusts to context - if the country of residence is UK vs US vs elsewhere. Should be doable. =)

**Comment by JamesPHoughton** [comment]
- notes from discussion with @tiamoin @nettaweinstein

- [ ] Ethnicity, we could find a single ethnicity measure that can be used globally?
- [ ] pull apart "gender" into more items (instead of "Other" say "Another Gender")
- [ ] Ethical questions about making anything mandatory (esp. disability), maybe make things optional?
- Is "crowd-work" the right language - does it even make sense to include this question (Paid Studies) Maybe "do you usually work on studies like this one during this time..."
- Comfort with english: Should the order of the responses be reversed - see if another survey has written this question. (Can we make the scale horizontal?)
- Getting education mapped across countries, it is important to have categories that are meaningful across countries.
- Put a slider in for some of the questions about liberal conservative?
- for income, center the income brackets around the country and make the bins appropriate for the country
- conservative/liberal is something that could be international

**Comment by xehu** [comment]
Random note: but can you change "is English your first language" to "is English your native language?" Because English is my second language but I speak it natively (due to learning it at age 5). I always struggle with those questions because I feel like I can't accurately answer them.

**Comment by markwhiting** [comment]
Are you thinking that some of these questions would depend on country? Might it be better to have those as a separate survey (it probably would be in the surveyor system but perhaps less so here)

**Comment by markwhiting** [comment]
Are you thinking that some of these questions would depend on country? Might it be better to have those as a separate survey (it probably would be in the surveyor system but perhaps less so here)

**Comment by TutiGomoka** [comment]
Also need to validate the country column so they can only enter valid text. Not emojis or something like that

**Comment by xehu** [comment]
Why are income min and income max included separately? I am a bit confused with how it works.

**Comment by TutiGomoka** [comment]
So: @JamesPHoughton I think the way in which the variables are listed in the codebook isn't the same way they are asked. E.g., we derive income min and income max from the one income question we ask

**Comment by TutiGomoka** [comment]
We also haven't been asking _usual time_ I think that was a variable in the previous study that Abdullah sent us

**Comment by markwhiting** [comment]
I think this is done, so hiding it from view on https://github.com/orgs/Watts-Lab/projects/8

**Comment by JamesPHoughton** [comment]
Should split off "do you normally do hits this time of the day" into a separate turk habits survey

**Comment by JamesPHoughton** [comment]
We have two demographics surveys now, a short and a long. We can continue to refine them as we go, i don't see it being a problem to modify the survey as these are not "reactive" (ie, demand effects) in the way that some others might be.
