### ISSUE TITLE
[Add] Autonomy Need Satisfaction

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#76]
Add a new survey to the repository according to the instructions in [the package README.md](https://github.com/Watts-Lab/surveys#readme).

# Survey Title
Autonomy Need Satisfaction

## Survey Source
Listening Validation Study

## Survey Overview 
Scale:
- 1 Not at all
- 2
- 3
- 4
- 5 Moderately
- 6
- 7
- 8
- 9 Very much

Questions:

1. I felt I could choose the direction of the conversation.
2. I felt I could not choose the content.
3. I felt I had a choice about what to share.
4. I felt I could take the discussion to important places.
5. I felt I could share sensitive topics.
6. I felt free to be who I am.
7. I had a say in what happened, and I could voice my opinion.
8. I felt controlled and pressured to be certain ways.

I think this could be productively asked as a matrix question?
## Aggregation
Reverse code questions 2 and 8.

# Tasks
- [ ] Create a new folder in surveys w/ descriptive, easy-to-read name `superSpecialSurvey/`
- [ ] Create SurveyJS .json file (*e.g.* `superSpecialSurvey/superSpecialSurvey.json`)
- [ ] Create a .bib file citing your references for the survey (*always:* `superSpecialSurvey/references.bib`)
- [ ] Create a readme markdown file to document (*always:* `superSpecialSurvey/README.md`) 
- [ ] Create file with function to aggregate survey data (*e.g.* `superSpecialSurvey.score.js`)
- [ ] Create a cypress test of the survey (e.g. `superSpecialSurvey.cy.jsx`)
- [ ] Create PR and link to this issue

**Comment by JamesPHoughton** [comment]
Hi @NettaWeinstein, @TiaMoin 
Noting this paragraph in the scales document - should we aggregate these items as two different outcomes?
> Two separate scales. Focus is on autonomy satisfaction / self-congruence items (“I felt free to be who I am.”, and “I had a say in what happens, and I could voice my opinion.”.“I felt controlled and pressured to be certain ways.” was not measured in Study 5 because it conceptually overlaps with both measures, but keeping it because it was used in Studies 1-4
