### ISSUE TITLE
[Add] Relatedness Need Satisfaction

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#77]
Add a new survey to the repository according to the instructions in [the package README.md](https://github.com/Watts-Lab/surveys#readme).

# Survey Title
Relatedness Need Satisfaction

## Survey Source
Listening validation study

### Scale:
- 1 Not at all
- 2
- 3
- 4
- 5 Moderately
- 6
- 7
- 8
- 9 Very much
@Tiamoin - this scale wasn't in the document explicitly, I'm assuming it's the same as for https://github.com/Watts-Lab/surveys/issues/76?

### questions
1. I felt closeness and intimacy.
2. I felt distance from others.
3. I felt cared about.

## Aggregation/scoring function
Reverse code question 2

# Tasks
- [ ] Create a new folder in surveys w/ descriptive, easy-to-read name `superSpecialSurvey/`
- [ ] Create SurveyJS .json file (*e.g.* `superSpecialSurvey/superSpecialSurvey.json`)
- [ ] Create a .bib file citing your references for the survey (*always:* `superSpecialSurvey/references.bib`)
- [ ] Create a readme markdown file to document (*always:* `superSpecialSurvey/README.md`) 
- [ ] Create file with function to aggregate survey data (*e.g.* `superSpecialSurvey.score.js`)
- [ ] Create a cypress test of the survey (e.g. `superSpecialSurvey.cy.jsx`)
- [ ] Create PR and link to this issue

**Comment by JamesPHoughton** [comment]
Complete in https://github.com/Watts-Lab/surveys/pull/91
