### ISSUE TITLE
[Add] Political Leanings Survey

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/surveys#90]
```json
{
"type": "radiogroup",
"name": "political_party_US",
"visibleIf": "{country_reside} = 'United States'",
"title": "Generally speaking, do you consider yourself a...\t",
"isRequired": true,
"choices": ["Democrat", "Republican", "Independent", "Other Party"]
}

        {
          "type": "radiogroup",
          "name": "political_social",
          "title": "Thinking about social issues, which of the following best describes your views?\t",
          "isRequired": false,
          "choices": [
            "Strongly Liberal",
            "Somewhat Liberal",
            "Moderate",
            "Somewhat Conservative",
            "Strongly Conservative"
          ]
        },
        {
          "type": "radiogroup",
          "name": "political_fiscal",
          "title": "Thinking about economic issues, which of the following best describes your views?\t",
          "isRequired": false,
          "choices": [
            "Strongly Liberal",
            "Somewhat Liberal",
            "Moderate",
            "Somewhat Conservative",
            "Strongly Conservative"
          ]
        },



    cy.get(`[data-name="political_social"] input[value="Moderate"]`).click({
      force: true,
    });

    cy.get(`[data-name="political_fiscal"] input[value="Moderate"]`).click({
      force: true,
    });

        cy.get(`[data-name="political_party_US"] input[value="Independent"]`).click(
      { force: true }
    );

```

Add a new survey to the repository according to the instructions in [the package README.md](https://github.com/Watts-Lab/surveys#readme).

# Survey Title

## Aggregation/scoring function

# Tasks
- [ ] Create a new folder in surveys w/ descriptive, easy-to-read name `superSpecialSurvey/`
- [ ] Create SurveyJS .json file (*e.g.* `superSpecialSurvey/superSpecialSurvey.json`)
- [ ] Create a .bib file citing your references for the survey (*always:* `superSpecialSurvey/references.bib`)
- [ ] Create a readme markdown file to document (*always:* `superSpecialSurvey/README.md`) 
- [ ] Create file with function to aggregate survey data (*e.g.* `superSpecialSurvey.score.js`)
- [ ] Create a cypress test of the survey (e.g. `superSpecialSurvey.cy.jsx`)
- [ ] Create PR and link to this issue
